# Generated by Django 4.0.5 on 2022-06-29 08:53

from django.db import migrations, models
import task.validators


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=255, validators=[task.validators.descriptionValidator]),
        ),
    ]
