# Generated by Django 4.0.5 on 2022-06-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='due',
        ),
    ]
